// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "serverUrl": string;
      "apiKey": string;
      "attachZhPdf": boolean;
      "attachEnPdf": boolean;
      "attachDualPdf": boolean;
      "batchDelayMs": number;
      "pollIntervalMs": number;
      "pollTimeoutMs": number;
    };
  }
}
